// module imports
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// file imports
import "./globals.css";
import LanguageSelector from "@/app/components/LanguageSelector";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
    params,
    // `url` should be a string representing the full current URL
}: Readonly<{
    children: React.ReactNode;
    params: {
        locale: string;
    };
}>) {
    // Get the full URL from the request context or window location
    const currentUrl = typeof window !== "undefined" ? window.location.href : '';

    return (
        <html lang={params.locale}>
            <body className={inter.className}>
                <LanguageSelector locale={params.locale} currentUrl={currentUrl} />
                {children}
            </body>
        </html>
    );
}